package com.ruizurraca.luziatestdavid.presentation.theme

import androidx.compose.ui.graphics.Color

internal val LuziaPrimaryLight = Color(0xFF6750A4)
internal val LuziaOnPrimaryLight = Color(0xFFFFFFFF)
internal val LuziaPrimaryContainerLight = Color(0xFFEADDFF)
internal val LuziaOnPrimaryContainerLight = Color(0xFF21005D)
internal val LuziaSecondaryLight = Color(0xFF625B71)
internal val LuziaOnSecondaryLight = Color(0xFFFFFFFF)
internal val LuziaSecondaryContainerLight = Color(0xFFE8DEF8)
internal val LuziaOnSecondaryContainerLight = Color(0xFF1D192B)
internal val LuziaTertiaryLight = Color(0xFF7D5260)
internal val LuziaOnTertiaryLight = Color(0xFFFFFFFF)
internal val LuziaTertiaryContainerLight = Color(0xFFFFD8E4)
internal val LuziaOnTertiaryContainerLight = Color(0xFF31111D)
internal val LuziaBackgroundLight = Color(0xFFFFFBFE)
internal val LuziaOnBackgroundLight = Color(0xFF1C1B1F)
internal val LuziaSurfaceLight = Color(0xFFFFFBFE)
internal val LuziaOnSurfaceLight = Color(0xFF1C1B1F)
internal val LuziaSurfaceVariantLight = Color(0xFFE7E0EC)
internal val LuziaOnSurfaceVariantLight = Color(0xFF49454F)
internal val LuziaErrorLight = Color(0xFFB3261E)
internal val LuziaOnErrorLight = Color(0xFFFFFFFF)

internal val LuziaPrimaryDark = Color(0xFFD0BCFF)
internal val LuziaOnPrimaryDark = Color(0xFF381E72)
internal val LuziaPrimaryContainerDark = Color(0xFF4F378B)
internal val LuziaOnPrimaryContainerDark = Color(0xFFEADDFF)
internal val LuziaSecondaryDark = Color(0xFFCCC2DC)
internal val LuziaOnSecondaryDark = Color(0xFF332D41)
internal val LuziaSecondaryContainerDark = Color(0xFF4A4458)
internal val LuziaOnSecondaryContainerDark = Color(0xFFE8DEF8)
internal val LuziaTertiaryDark = Color(0xFFEFB8C8)
internal val LuziaOnTertiaryDark = Color(0xFF492532)
internal val LuziaTertiaryContainerDark = Color(0xFF633B48)
internal val LuziaOnTertiaryContainerDark = Color(0xFFFFD8E4)
internal val LuziaBackgroundDark = Color(0xFF1C1B1F)
internal val LuziaOnBackgroundDark = Color(0xFFE6E1E5)
internal val LuziaSurfaceDark = Color(0xFF1C1B1F)
internal val LuziaOnSurfaceDark = Color(0xFFE6E1E5)
internal val LuziaSurfaceVariantDark = Color(0xFF49454F)
internal val LuziaOnSurfaceVariantDark = Color(0xFFCAC4D0)
internal val LuziaErrorDark = Color(0xFFF2B8B5)
internal val LuziaOnErrorDark = Color(0xFF601410)
